name: e2e_tests
description: equatable_annotations example
version: 1.0.0

publish_to: "none"

environment:
  sdk: ^3.0.0

dependencies:
  equatable_annotations:
  equatable: ^2.0.7

dev_dependencies:
  build_runner: ^2.4.7
  build_test: ^3.3.3
  equatable_gen:
  lints: ^6.0.0
  test: ^1.26.3
  derry: ^1.5.0
  generator_test: ^0.5.0

scripts: scripts.yaml
