name: equatable_gen
description: Automatically creates 'props' getters for classes using the equatable package.
version: 1.2.0
homepage: https://github.com/mrgnhnt96/equatable_gen/issues
issue_tracker: https://github.com/mrgnhnt96/equatable_gen/issues/issues

funding:
  - https://github.com/sponsors/mrgnhnt96

topics:
  - equatable
  - equality
  - equals
  - props
  - generator

environment:
  sdk: ^3.7.0

dependencies:
  analyzer: ">=7.4.0 <9.0.0"
  equatable_annotations: ^1.1.0
  build: ">=3.1.0 <5.0.0"
  code_builder: ^4.10.1
  change_case: ^2.2.0
  dart_style: ^3.1.1
  equatable: ^2.0.7
  meta: ">=1.0.0 <2.0.0"
  source_gen: ">=3.1.0 <5.0.0"
  path: ">=1.0.0 <2.0.0"
  source_span: ^1.10.1
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.7.1
  build_test: ^3.3.3
  generator_test: ">=0.5.0 <1.0.0"
  lints: ">=5.1.1 <7.0.0"
  test: ^1.26.3
